// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.20.1
// source: common.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CommonServiceClient is the client API for CommonService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CommonServiceClient interface {
	SetLogLevel(ctx context.Context, in *SetLogLevelRequest, opts ...grpc.CallOption) (*SetLogLevelResponse, error)
	DownloadPprofFile(ctx context.Context, in *DownloadPprofFileRequest, opts ...grpc.CallOption) (CommonService_DownloadPprofFileClient, error)
}

type commonServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCommonServiceClient(cc grpc.ClientConnInterface) CommonServiceClient {
	return &commonServiceClient{cc}
}

func (c *commonServiceClient) SetLogLevel(ctx context.Context, in *SetLogLevelRequest, opts ...grpc.CallOption) (*SetLogLevelResponse, error) {
	out := new(SetLogLevelResponse)
	err := c.cc.Invoke(ctx, "/pb.CommonService/setLogLevel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commonServiceClient) DownloadPprofFile(ctx context.Context, in *DownloadPprofFileRequest, opts ...grpc.CallOption) (CommonService_DownloadPprofFileClient, error) {
	stream, err := c.cc.NewStream(ctx, &CommonService_ServiceDesc.Streams[0], "/pb.CommonService/DownloadPprofFile", opts...)
	if err != nil {
		return nil, err
	}
	x := &commonServiceDownloadPprofFileClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type CommonService_DownloadPprofFileClient interface {
	Recv() (*FileChunk, error)
	grpc.ClientStream
}

type commonServiceDownloadPprofFileClient struct {
	grpc.ClientStream
}

func (x *commonServiceDownloadPprofFileClient) Recv() (*FileChunk, error) {
	m := new(FileChunk)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// CommonServiceServer is the server API for CommonService service.
// All implementations should embed UnimplementedCommonServiceServer
// for forward compatibility
type CommonServiceServer interface {
	SetLogLevel(context.Context, *SetLogLevelRequest) (*SetLogLevelResponse, error)
	DownloadPprofFile(*DownloadPprofFileRequest, CommonService_DownloadPprofFileServer) error
}

// UnimplementedCommonServiceServer should be embedded to have forward compatible implementations.
type UnimplementedCommonServiceServer struct {
}

func (UnimplementedCommonServiceServer) SetLogLevel(context.Context, *SetLogLevelRequest) (*SetLogLevelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetLogLevel not implemented")
}
func (UnimplementedCommonServiceServer) DownloadPprofFile(*DownloadPprofFileRequest, CommonService_DownloadPprofFileServer) error {
	return status.Errorf(codes.Unimplemented, "method DownloadPprofFile not implemented")
}

// UnsafeCommonServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CommonServiceServer will
// result in compilation errors.
type UnsafeCommonServiceServer interface {
	mustEmbedUnimplementedCommonServiceServer()
}

func RegisterCommonServiceServer(s grpc.ServiceRegistrar, srv CommonServiceServer) {
	s.RegisterService(&CommonService_ServiceDesc, srv)
}

func _CommonService_SetLogLevel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetLogLevelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommonServiceServer).SetLogLevel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.CommonService/setLogLevel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommonServiceServer).SetLogLevel(ctx, req.(*SetLogLevelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommonService_DownloadPprofFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DownloadPprofFileRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CommonServiceServer).DownloadPprofFile(m, &commonServiceDownloadPprofFileServer{stream})
}

type CommonService_DownloadPprofFileServer interface {
	Send(*FileChunk) error
	grpc.ServerStream
}

type commonServiceDownloadPprofFileServer struct {
	grpc.ServerStream
}

func (x *commonServiceDownloadPprofFileServer) Send(m *FileChunk) error {
	return x.ServerStream.SendMsg(m)
}

// CommonService_ServiceDesc is the grpc.ServiceDesc for CommonService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CommonService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.CommonService",
	HandlerType: (*CommonServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "setLogLevel",
			Handler:    _CommonService_SetLogLevel_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "DownloadPprofFile",
			Handler:       _CommonService_DownloadPprofFile_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "common.proto",
}
