// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.20.1
// source: panda-auth.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PandaAuthClient is the client API for PandaAuth service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PandaAuthClient interface {
	// SayHello 方法
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error)
}

type pandaAuthClient struct {
	cc grpc.ClientConnInterface
}

func NewPandaAuthClient(cc grpc.ClientConnInterface) PandaAuthClient {
	return &pandaAuthClient{cc}
}

func (c *pandaAuthClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error) {
	out := new(HelloResponse)
	err := c.cc.Invoke(ctx, "/pb.PandaAuth/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PandaAuthServer is the server API for PandaAuth service.
// All implementations should embed UnimplementedPandaAuthServer
// for forward compatibility
type PandaAuthServer interface {
	// SayHello 方法
	SayHello(context.Context, *HelloRequest) (*HelloResponse, error)
}

// UnimplementedPandaAuthServer should be embedded to have forward compatible implementations.
type UnimplementedPandaAuthServer struct {
}

func (UnimplementedPandaAuthServer) SayHello(context.Context, *HelloRequest) (*HelloResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}

// UnsafePandaAuthServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PandaAuthServer will
// result in compilation errors.
type UnsafePandaAuthServer interface {
	mustEmbedUnimplementedPandaAuthServer()
}

func RegisterPandaAuthServer(s grpc.ServiceRegistrar, srv PandaAuthServer) {
	s.RegisterService(&PandaAuth_ServiceDesc, srv)
}

func _PandaAuth_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PandaAuthServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.PandaAuth/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PandaAuthServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PandaAuth_ServiceDesc is the grpc.ServiceDesc for PandaAuth service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PandaAuth_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.PandaAuth",
	HandlerType: (*PandaAuthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _PandaAuth_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "panda-auth.proto",
}
